# Generated by Django 5.2.8 on 2025-11-24 19:07

import tenants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='subdomain',
            field=models.SlugField(help_text='Identificador único na URL (ex: oficina-centro)', max_length=100, unique=True, validators=[tenants.validators.validate_subdomain], verbose_name='Subdomínio'),
        ),
    ]
